name: task3

on:
  push:
    branches:
      - main

jobs:
  job-a:
    strategy:
      matrix:
        env: ["prod","dev","staging"]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying to ${{ matrix.env}}"

  job-b:
    needs: job-a
    if: seccess()
    runs-on: ubuntu-latest
    steps:
      - run: echo "All environments deployed successfully"

