name: task1

on:
  push:
    branches:
      - main

jobs:
  job-a:
    runs-on: ubuntu-latest
    steps:
      - run: echo "my_name=Matan" >> $GITHUB_ENV
      - run: echo "my name is ${{ env.my_name }}"


