name: task 

on:
  push:
    branches:
      - main
  workflow_dispatch:
    

jobs:
  job-a:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger manually!"
    

  job-b:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trigger by push!"
  