name: task-1

on:
  push:
    branches:
      - main

jobs:
  job-a:
    runs-on: ubuntu-latest
    outputs:
      sum: ${{ steps.num.outputs.sum}}
    steps:
      - id: num 
        run: echo "sum=10" >> $GITHUB_OUTPUT

  job-b:
    needs: job-a
    runs-on: ubuntu-latest
    steps:
      - run: echo "The sum is :${{ needs.job-a.outputs.sum }}"
