name: task2

on:
  push:
    branches:
      - main

jobs:
  job-a:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - run: sleep 60

